spring:
  application:
    name: API-Gateway
  #security:
   # user:
    #  name: '"gateway"'
     # password: '"root"'
      
eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
   
  
management:
  endpoints:
    web:
      exposure:
        include: info, health, routes
server:
  port: 8100

zuul:
  routes:
    admin-service:
      path: /agroadmin/**
      serviceId: ADMIN-SERVICE
    dealer-service:
      path: /agrodealer/**
      serviceId: DEALER-SERVICE
    farmer-service:
      path: /agrofarmer/**
      serviceId: FARMER-SERVICE
# Increase the Hystrix timeout to 60s (for all)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
